name: Build and Push to repo

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to repo
        uses: docker/login-action@v3
        with:
          registry: git.devhack.net
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: git.devhack.net/${{ github.repository }}:latest
